services:
  - type: web
    name: kural-api
    env: node
    buildCommand: npm install && npm run build:db
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/couplets
    github:
      branch: main
      deploy_on_push: true
      repo: karuna-1001/kural
    autoDeploy: true